/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

/**
 *
 * @author Usuario
 */
public class VentanaInicial extends javax.swing.JFrame {

    private String usuario1,usuario2;
    public VentanaInicial() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        botonComenzar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        labelUsuario1 = new javax.swing.JLabel();
        labelUsuario2 = new javax.swing.JLabel();
        nombreUsuario1 = new javax.swing.JTextField();
        nombreUsuario2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        etUsuario1 = new javax.swing.JLabel();
        etUsuario2 = new javax.swing.JLabel();
        botonComenzar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        titulo.setText("Tres en Raya");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 43, -1, -1));

        labelUsuario1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelUsuario1.setText("Digite el nombre del usuario 1:");
        jPanel1.add(labelUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 172, -1, -1));

        labelUsuario2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelUsuario2.setText("Digite el nombre del usuario 2:");
        jPanel1.add(labelUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 225, -1, -1));

        nombreUsuario1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanel1.add(nombreUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 173, 305, 30));

        nombreUsuario2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        nombreUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuario2ActionPerformed(evt);
            }
        });
        jPanel1.add(nombreUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 221, 305, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tresEnRaya.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 309, 251, 196));

        botonGuardar.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 309, -1, -1));

        etUsuario1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jPanel1.add(etUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 420, 30));

        etUsuario2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jPanel1.add(etUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 420, 40));

        botonComenzar.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        botonComenzar.setText("Comenzar Juego!!");
        botonComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComenzarActionPerformed(evt);
            }
        });
        jPanel1.add(botonComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 452, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuario2ActionPerformed
        
    }//GEN-LAST:event_nombreUsuario2ActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        usuario1 = nombreUsuario1.getText();
        usuario2 = nombreUsuario2.getText();
        
        botonGuardar.setVisible(false);
        etUsuario1.setText(usuario1 +", jugara primero, su ficha es X");
        etUsuario2.setText(usuario2 + ", jugara segundo, su ficha es O");
        botonComenzar.setVisible(true);
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComenzarActionPerformed
        VentanaPrincipal vp = new VentanaPrincipal(usuario1,usuario2);
        vp.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonComenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComenzar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JLabel etUsuario1;
    private javax.swing.JLabel etUsuario2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelUsuario1;
    private javax.swing.JLabel labelUsuario2;
    private javax.swing.JTextField nombreUsuario1;
    private javax.swing.JTextField nombreUsuario2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
